window.CANTON_AGENDA_DATA = {
  "Fase 1": [
    {
      "id": "97",
      "orden": "1",
      "dia": "1",
      "area": "A",
      "pabellon": "1.1",
      "stand": "1.1C33-35，1.1D10-12",
      "proveedor": "Hebei Orient ADMA Orientflex",
      "visita": "Principal en esta fase",
      "rubro": "Mangueras",
      "descripcion": "Mangueras para hormigón, abrasivos, agua, aire e hidráulica; acoples y conexiones.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "30",
      "orden": "2",
      "dia": "1",
      "area": "A",
      "pabellon": "1.1",
      "stand": "1.1H47",
      "proveedor": "bodo plastics co., ltd",
      "visita": "Principal en esta fase",
      "rubro": "Plásticos",
      "descripcion": "La captura indica una empresa de plásticos; nombre legal y catálogo pendientes de identificar.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "60",
      "orden": "3",
      "dia": "1",
      "area": "A",
      "pabellon": "1.1",
      "stand": "1.1J25",
      "proveedor": "CHANGZHOU ZHONGTIAN FIRE-PROOF DECORATIVE SHEETS CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Laminados decorativos",
      "descripcion": "Placas decorativas con prestaciones frente al fuego; clasificación y usos a confirmar.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "82",
      "orden": "4",
      "dia": "1",
      "area": "A",
      "pabellon": "1.1",
      "stand": "1.1M04",
      "proveedor": "Foshan Greenzone Co., LTD",
      "visita": "Principal en esta fase",
      "rubro": "WPC",
      "descripcion": "Soluciones decorativas de madera compuesta; decks, revestimientos y otros formatos a confirmar.",
      "otrosStands": "F2: 13.0A22-23，13.0B01-02",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "91",
      "orden": "5",
      "dia": "1",
      "area": "A",
      "pabellon": "4.0",
      "stand": "4.0B12-13",
      "proveedor": "Tekpac Engineering",
      "visita": "Principal en esta fase",
      "rubro": "Maquinaria liviana",
      "descripcion": "Canguros, placas, rodillos, vibradores, reglas y fratachadoras; comparar garantía para alquiler.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "90",
      "orden": "6",
      "dia": "1",
      "area": "A",
      "pabellon": "4.0",
      "stand": "4.0D13",
      "proveedor": "Masalta Engineering",
      "visita": "Principal en esta fase",
      "rubro": "Compactación y alquiler",
      "descripcion": "Canguros, placas, rodillos, vibradores, reglas, helicópteros, cortadoras y mezcladoras.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "92",
      "orden": "7",
      "dia": "1",
      "area": "A",
      "pabellon": "4.0",
      "stand": "4.0H13",
      "proveedor": "Zhengzhou Unique Industrial Equipment UNIQUEMAC",
      "visita": "Principal en esta fase",
      "rubro": "Producción y bombeo",
      "descripcion": "Plantas dosificadoras, mezcladoras con bomba, autocargables y equipos de áridos; confirmar fabricante por equipo.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "73",
      "orden": "8",
      "dia": "1",
      "area": "A",
      "pabellon": "4.1",
      "stand": "4.1D41-42，4.1E07-08",
      "proveedor": "ZHONGSHAN LIANCHANG CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Climatización",
      "descripcion": "Equipos de climatización portátiles y deshumidificación.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "8",
      "orden": "9",
      "dia": "1",
      "area": "A",
      "pabellon": "5.1",
      "stand": "5.1B35-36，5.1C09-10",
      "proveedor": "Guangdong Gemake Electric Appliance Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Agua caliente",
      "descripcion": "Equipos eléctricos para calentamiento de agua; modelos y capacidades a confirmar.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "76",
      "orden": "10",
      "dia": "1",
      "area": "A",
      "pabellon": "8.0",
      "stand": "8.0J20",
      "proveedor": "QINGDAO HIPAD INTERNATIONAL TRADE CO., LTD",
      "visita": "Alternativa / otra línea",
      "rubro": "Herrajes para aberturas",
      "descripcion": "Herrajes para puertas y ventanas, rodillos, manijas y cerraduras.",
      "otrosStands": "F1: 9.1B46",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "71",
      "orden": "11",
      "dia": "1",
      "area": "A",
      "pabellon": "8.0",
      "stand": "8.0Q01",
      "proveedor": "Shandong Aolan Drone Science and Technology Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Drones agrícolas",
      "descripcion": "Drones para aplicaciones agrícolas; carga, autonomía y funciones a confirmar.",
      "otrosStands": "F1: 20.2C22",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "72",
      "orden": "12",
      "dia": "1",
      "area": "A",
      "pabellon": "8.0",
      "stand": "8.0Q02",
      "proveedor": "Shandong Joyance Intelligence Technology Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Drones agrícolas",
      "descripcion": "Drones y equipos inteligentes para trabajos agrícolas; catálogo a confirmar.",
      "otrosStands": "F1: 20.2C21",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "76",
      "orden": "13",
      "dia": "2",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1B46",
      "proveedor": "QINGDAO HIPAD INTERNATIONAL TRADE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Herrajes para aberturas",
      "descripcion": "Herrajes para puertas y ventanas, rodillos, manijas y cerraduras.",
      "otrosStands": "F1: 8.0J20",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "27",
      "orden": "14",
      "dia": "2",
      "area": "B",
      "pabellon": "10.1",
      "stand": "10.1M12",
      "proveedor": "Foshan Hero Metal Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Perfiles de terminación",
      "descripcion": "Perfiles para cerámicos, transiciones de pisos, zócalos y accesorios de colocación.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "1",
      "orden": "15",
      "dia": "2",
      "area": "B",
      "pabellon": "10.2",
      "stand": "10.2J17-18",
      "proveedor": "KANGTON INDUSTRY, INC.",
      "visita": "Principal en esta fase",
      "rubro": "Pisos y puertas",
      "descripcion": "Pisos y puertas para proyectos residenciales y comerciales.",
      "otrosStands": "F2: 12.2B31-33",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "26",
      "orden": "16",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1C44",
      "proveedor": "DINGZHOU XINWANG METAL WIRE MESH CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Mallas metálicas",
      "descripcion": "Alambres y mallas metálicas para cerramientos y usos industriales.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "42",
      "orden": "17",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1G15-16",
      "proveedor": "3H Inc.",
      "visita": "Principal en esta fase",
      "rubro": "Herrajes para aberturas",
      "descripcion": "Manijas, bisagras, cierres y sistemas de herrajes para puertas y ventanas.",
      "otrosStands": "F2: 12.1G43-44",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "45",
      "orden": "18",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1I21",
      "proveedor": "JIANGSU TIANYU FIBRE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Fibra de vidrio",
      "descripcion": "Mallas de fibra de vidrio, cintas y productos de refuerzo para construcción.",
      "otrosStands": "F2: 12.1E39",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "93",
      "orden": "19",
      "dia": "2",
      "area": "B",
      "pabellon": "12.0",
      "stand": "12.0B37-38",
      "proveedor": "Hunan TANT Tiantuo",
      "visita": "Principal en esta fase",
      "rubro": "Bombeo",
      "descripcion": "Bombas remolcables, mezcladoras con bomba, bombas con pluma y brazos distribuidores.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "94",
      "orden": "20",
      "dia": "2",
      "area": "B",
      "pabellon": "12.0",
      "stand": "12.0C25-27",
      "proveedor": "Shandong VANSE Machinery",
      "visita": "Principal en esta fase",
      "rubro": "Pisos industriales",
      "descripcion": "Niveladoras láser, fratachadoras, esparcidores, minidumpers, juntas y fibras.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "75",
      "orden": "21",
      "dia": "2",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1L08",
      "proveedor": "HEBEI MINMETALS CO., LTD.",
      "visita": "Alternativa / otra línea",
      "rubro": "Metales y ferretería",
      "descripcion": "Proveedor de artículos metálicos y ferretería; línea concreta a confirmar.",
      "otrosStands": "F3: 9.1L37; F1: 9.2F45; F1: 13.1A08-10，13.1B13-15; F2: 8.1D37-38，8.1E11-12; F2: 11.3K30; F2: 13.1B35-36，13.1C10-11",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "95",
      "orden": "22",
      "dia": "2",
      "area": "B",
      "pabellon": "13.0",
      "stand": "13.0A20-25",
      "proveedor": "SINOTRUK Hubei Huawin",
      "visita": "Principal en esta fase",
      "rubro": "Vehículos y repuestos",
      "descripcion": "Mixers y bombas con pluma; 13.0 vehículos y 9.3 repuestos.",
      "otrosStands": "F1: 9.3H09",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "75",
      "orden": "23",
      "dia": "2",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1A08-10，13.1B13-15",
      "proveedor": "HEBEI MINMETALS CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Metales y ferretería",
      "descripcion": "Proveedor de artículos metálicos y ferretería; línea concreta a confirmar.",
      "otrosStands": "F3: 9.1L37; F1: 9.2F45; F1: 12.1L08; F2: 8.1D37-38，8.1E11-12; F2: 11.3K30; F2: 13.1B35-36，13.1C10-11",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "59",
      "orden": "24",
      "dia": "2",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1A18",
      "proveedor": "DINGZHOU BEST HARDWARE CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Ferretería",
      "descripcion": "Productos de ferretería; confirmar líneas de alambre, mallas u otros artículos.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "105",
      "orden": "25",
      "dia": "2",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1H45",
      "proveedor": "Aceccse Hangzhou Composite",
      "visita": "Principal en esta fase",
      "rubro": "Cilindros GLP",
      "descripcion": "Cilindros compuestos livianos para GLP; no equivalen a tubos de alta presión para gases industriales.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "7",
      "orden": "26",
      "dia": "2",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1J01",
      "proveedor": "BENYU CASTERS & WHEELS CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Ruedas industriales",
      "descripcion": "Ruedas y soportes giratorios para carros, muebles y equipos.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "75",
      "orden": "27",
      "dia": "2",
      "area": "B",
      "pabellon": "9.2",
      "stand": "9.2F45",
      "proveedor": "HEBEI MINMETALS CO., LTD.",
      "visita": "Alternativa / otra línea",
      "rubro": "Metales y ferretería",
      "descripcion": "Proveedor de artículos metálicos y ferretería; línea concreta a confirmar.",
      "otrosStands": "F3: 9.1L37; F1: 13.1A08-10，13.1B13-15; F1: 12.1L08; F2: 8.1D37-38，8.1E11-12; F2: 11.3K30; F2: 13.1B35-36，13.1C10-11",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "95",
      "orden": "28",
      "dia": "2",
      "area": "B",
      "pabellon": "9.3",
      "stand": "9.3H09",
      "proveedor": "SINOTRUK Hubei Huawin",
      "visita": "Alternativa / otra línea",
      "rubro": "Vehículos y repuestos",
      "descripcion": "Mixers y bombas con pluma; 13.0 vehículos y 9.3 repuestos.",
      "otrosStands": "F1: 13.0A20-25",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "104",
      "orden": "29",
      "dia": "3",
      "area": "D",
      "pabellon": "18.1",
      "stand": "18.1F10-11",
      "proveedor": "CAN GAS",
      "visita": "Principal en esta fase",
      "rubro": "Generación y llenado",
      "descripcion": "Generadores de oxígeno y nitrógeno, purificación, compresión y llenado de cilindros.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "112",
      "orden": "30",
      "dia": "3",
      "area": "D",
      "pabellon": "19.1",
      "stand": "19.1A09-B15",
      "proveedor": "SENFENG",
      "visita": "Principal en esta fase",
      "rubro": "Soldadura y automatización",
      "descripcion": "Soldadura láser manual/robotizada, cobot de arco y paneladora; bloque A09-B15 publicado, confirmar ubicación exacta.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "38",
      "orden": "31",
      "dia": "3",
      "area": "D",
      "pabellon": "19.1",
      "stand": "19.1D19",
      "proveedor": "HEBEI BAOFENG STEEL STRUCTURE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Estructuras y módulos",
      "descripcion": "Estructuras de acero y soluciones prefabricadas; modelos y sistemas a confirmar.",
      "otrosStands": "F2: 11.2L34",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "96",
      "orden": "32",
      "dia": "3",
      "area": "D",
      "pabellon": "19.1",
      "stand": "19.1D32-33",
      "proveedor": "CUS GROUP Zhengzhou City Unites Steel Industrial",
      "visita": "Principal en esta fase",
      "rubro": "Bombas y estructuras",
      "descripcion": "Chapas y estructuras; catálogo de Cantón incluye bombas. Aclarar fabricante, garantía y repuestos.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "61",
      "orden": "33",
      "dia": "3",
      "area": "D",
      "pabellon": "19.1",
      "stand": "19.1G36-37，19.1H10-11",
      "proveedor": "ACCURL CNC MACHINE (ANHUI) MANUFACTORY CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Maquinaria metalúrgica",
      "descripcion": "Maquinaria CNC para plegado y corte de chapa.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "113",
      "orden": "34",
      "dia": "3",
      "area": "D",
      "pabellon": "19.1",
      "stand": "19.1K16-18",
      "proveedor": "HARSLE",
      "visita": "Principal en esta fase",
      "rubro": "Asistencia al plegado",
      "descripcion": "Seguidores de chapa, herramientas, amarres rápidos, punzonadoras y MultiPro; evaluar adaptación a plegadora.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "114",
      "orden": "35",
      "dia": "3",
      "area": "D",
      "pabellon": "19.1",
      "stand": "19.1K30-31",
      "proveedor": "RAYVANBO",
      "visita": "Principal en esta fase",
      "rubro": "Movimiento de chapas",
      "descripcion": "Pulpo de vacío, grúas, pórticos, polipastos y mesas elevadoras; verificar capacidad y retención ante fallo.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "115",
      "orden": "36",
      "dia": "3",
      "area": "D",
      "pabellon": "20.1",
      "stand": "20.1A07-12，20.1B12-17",
      "proveedor": "GWEIKE",
      "visita": "Principal en esta fase",
      "rubro": "Soldadura",
      "descripcion": "Equipos láser y soldadura; comparar trabajo sobre piezas reales, deformación y consumibles.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "116",
      "orden": "37",
      "dia": "3",
      "area": "D",
      "pabellon": "20.1",
      "stand": "20.1F23",
      "proveedor": "DURMAPRESS",
      "visita": "Principal en esta fase",
      "rubro": "Operaciones de chapa",
      "descripcion": "Plegado, corte y operaciones complementarias; evaluar punzonado, herramientas y terminación.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "99",
      "orden": "38",
      "dia": "3",
      "area": "D",
      "pabellon": "20.1",
      "stand": "20.1H40-41",
      "proveedor": "Guangxi Hongfa Heavy Machinery",
      "visita": "Principal en esta fase",
      "rubro": "Prefabricados y producción",
      "descripcion": "Equipos de fabricación de bloques, paneles y producción de hormigón; comparar línea y puesta en marcha.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "98",
      "orden": "39",
      "dia": "3",
      "area": "D",
      "pabellon": "20.1",
      "stand": "20.1J42",
      "proveedor": "Shandong Tianyi Machinery TANY",
      "visita": "Principal en esta fase",
      "rubro": "Prefabricados",
      "descripcion": "Líneas de paneles cemento/EPS, AAC, GRC, yeso y elementos prefabricados PC.",
      "otrosStands": "F2: 13.2L21",
      "fase": "Fase 1",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "64",
      "orden": "40",
      "dia": "3",
      "area": "D",
      "pabellon": "20.1",
      "stand": "20.1J43",
      "proveedor": "Zhangzhou Tai Heng Motor Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Motores y automatización",
      "descripcion": "Motores para automatización de cierres; aplicaciones y modelos a confirmar.",
      "otrosStands": "",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "72",
      "orden": "41",
      "dia": "3",
      "area": "D",
      "pabellon": "20.2",
      "stand": "20.2C21",
      "proveedor": "Shandong Joyance Intelligence Technology Co., Ltd.",
      "visita": "Alternativa / otra línea",
      "rubro": "Drones agrícolas",
      "descripcion": "Drones y equipos inteligentes para trabajos agrícolas; catálogo a confirmar.",
      "otrosStands": "F1: 8.0Q02",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "71",
      "orden": "42",
      "dia": "3",
      "area": "D",
      "pabellon": "20.2",
      "stand": "20.2C22",
      "proveedor": "Shandong Aolan Drone Science and Technology Co., Ltd",
      "visita": "Alternativa / otra línea",
      "rubro": "Drones agrícolas",
      "descripcion": "Drones para aplicaciones agrícolas; carga, autonomía y funciones a confirmar.",
      "otrosStands": "F1: 8.0Q01",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "69",
      "orden": "43",
      "dia": "3",
      "area": "D",
      "pabellon": "20.2",
      "stand": "20.2H37-39，20.2I10-12",
      "proveedor": "LUMI LEGEND CORPORATION",
      "visita": "Principal en esta fase",
      "rubro": "Soportes y ergonomía",
      "descripcion": "Soportes para pantallas y soluciones de montaje y ergonomía.",
      "otrosStands": "F2: 11.3B35-36，11.3C12-13",
      "fase": "Fase 1",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    }
  ],
  "Fase 2": [
    {
      "id": "87",
      "orden": "1",
      "dia": "1",
      "area": "B",
      "pabellon": "9.0",
      "stand": "9.0B09-11",
      "proveedor": "SPARELAX CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Spa e hidromasaje",
      "descripcion": "Spas, hidromasajes y equipos relacionados con piscinas.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "88",
      "orden": "2",
      "dia": "1",
      "area": "B",
      "pabellon": "9.0",
      "stand": "9.0C01-02",
      "proveedor": "GUANGZHOU MONALISA BATH WARE CO., LTD",
      "visita": "Alternativa / otra línea",
      "rubro": "Baño e hidromasaje",
      "descripcion": "Equipamiento de baño e hidromasaje; modelos y catálogo a confirmar.",
      "otrosStands": "F3: 9.2B23-24，9.2A01-02; F2: 10.1E32-38，10.1F13-19",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "55",
      "orden": "3",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1A06-17",
      "proveedor": "Guangdong Huayi Plumbing Fittings Industry Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Grifería",
      "descripcion": "Grifería y accesorios para instalaciones de agua y baño.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "32",
      "orden": "4",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1D33-35，9.1E11-13",
      "proveedor": "Aifeiling Sanitary Wares Technology Group Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento sanitario y accesorios para baño; catálogo a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "36",
      "orden": "5",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1F26-27，9.1G18-19",
      "proveedor": "KAIPING LIPU SANITARY WARE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Grifería",
      "descripcion": "Grifería y accesorios sanitarios; catálogo específico a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "12",
      "orden": "6",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1H24-25",
      "proveedor": "Zhejiang Ballee Sanitary Wares Technology Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento para baño; catálogo específico a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "63",
      "orden": "7",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1H37-38",
      "proveedor": "Nokite Eco Smart Water Heating Systems (Guangdong) Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Agua caliente",
      "descripcion": "Sistemas de calentamiento de agua; tecnología y catálogo a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "24",
      "orden": "8",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1L35",
      "proveedor": "GUANGDONG ADEAR SANITARY WARE INDUSTRY CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento para baño; productos específicos a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "40",
      "orden": "9",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1N01",
      "proveedor": "Fujian Litu Sanitary Ware Technology Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Productos sanitarios y accesorios de baño; catálogo a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "5",
      "orden": "10",
      "dia": "1",
      "area": "B",
      "pabellon": "10.1",
      "stand": "10.1A08-17",
      "proveedor": "HUIDA SANITARY WARE CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Sanitarios cerámicos y equipamiento integral para baño.",
      "otrosStands": "F2: 13.2C08-13",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "10",
      "orden": "11",
      "dia": "1",
      "area": "B",
      "pabellon": "10.1",
      "stand": "10.1D01-03",
      "proveedor": "Tengzhou Yoway Electronic Technology Co., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Espejos y muebles de baño",
      "descripcion": "Espejos iluminados y gabinetes para baño.",
      "otrosStands": "F2: 11.3B27-28",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "88",
      "orden": "12",
      "dia": "1",
      "area": "B",
      "pabellon": "10.1",
      "stand": "10.1E32-38，10.1F13-19",
      "proveedor": "GUANGZHOU MONALISA BATH WARE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Baño e hidromasaje",
      "descripcion": "Equipamiento de baño e hidromasaje; modelos y catálogo a confirmar.",
      "otrosStands": "F3: 9.2B23-24，9.2A01-02; F2: 9.0C01-02",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "67",
      "orden": "13",
      "dia": "1",
      "area": "B",
      "pabellon": "10.1",
      "stand": "10.1L16",
      "proveedor": "CHAOZHOU FARNS CERAMICS INDUSTRIAL CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios cerámicos",
      "descripcion": "Productos cerámicos para baño; modelos y gama a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "23",
      "orden": "14",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1C01-02",
      "proveedor": "GUANGDONG WITBORN SANITARY WARE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Productos y equipamiento sanitario para baño; gama a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "83",
      "orden": "15",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1C37-38",
      "proveedor": "BARANA INTERNATIONAL LTD",
      "visita": "Principal en esta fase",
      "rubro": "Baño y terminaciones",
      "descripcion": "Productos para baño y construcción; catálogo seleccionado a confirmar.",
      "otrosStands": "F2: 13.2H31-32，13.2I17-18",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "39",
      "orden": "16",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1F47-48，11.1G01-02",
      "proveedor": "Guangdong Gres Sanitary Ware Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento para baño; gama de productos a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "2",
      "orden": "17",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1H13-16，11.1G31-34",
      "proveedor": "Guangzhou Selaqua Sanitary Ware Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento sanitario y productos para baño; líneas específicas a confirmar.",
      "otrosStands": "F3: 10.2F48",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "19",
      "orden": "18",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1I23-24",
      "proveedor": "Henan Lanjan Ceramics Co., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Cerámicos",
      "descripcion": "Productos cerámicos; confirmar si la línea seleccionada corresponde a sanitarios o revestimientos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "70",
      "orden": "19",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1J17-18，11.1I31-32",
      "proveedor": "Shenzhen Jianyuanda Mirror Technology Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Espejos",
      "descripcion": "Espejos para baño y decoración; iluminación y funciones a confirmar. Revisar escritura legal del nombre.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "46",
      "orden": "20",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1K26",
      "proveedor": "HANGZHOU KINGSUN SANITARY WARE CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento para baño; líneas de muebles, espejos u otros productos a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "35",
      "orden": "21",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1K47",
      "proveedor": "TAIHE SANITARY WARES PRODUCTS CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Productos sanitarios para baño; líneas y materiales a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "25",
      "orden": "22",
      "dia": "2",
      "area": "B",
      "pabellon": "11.1",
      "stand": "11.1L38",
      "proveedor": "GUANG DONG MIN JIE SANITARY WARE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento sanitario; grifería y otras líneas a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "6",
      "orden": "23",
      "dia": "2",
      "area": "B",
      "pabellon": "11.2",
      "stand": "11.2J43",
      "proveedor": "Dongguan Hopehead Pipe Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Tuberías",
      "descripcion": "Tuberías y conexiones para instalaciones; materiales y normas a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "34",
      "orden": "24",
      "dia": "2",
      "area": "B",
      "pabellon": "11.2",
      "stand": "11.2K01",
      "proveedor": "Weifang Henglida Steel Structure Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Estructuras y módulos",
      "descripcion": "Estructuras de acero y edificios prefabricados para diferentes usos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "54",
      "orden": "25",
      "dia": "2",
      "area": "B",
      "pabellon": "11.2",
      "stand": "11.2L16",
      "proveedor": "Wiskind Architectural Steel Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Paneles y chapas",
      "descripcion": "Sistemas metálicos, paneles y envolventes para edificios.",
      "otrosStands": "F2: 12.0C11-12，12.0D11",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "102",
      "orden": "26",
      "dia": "2",
      "area": "B",
      "pabellon": "11.2",
      "stand": "11.2L27",
      "proveedor": "Yutian Zhitai Steel Fiber",
      "visita": "Principal en esta fase",
      "rubro": "Refuerzo",
      "descripcion": "Fibras de acero para hormigón; comparar geometría, dosificación y ensayos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "38",
      "orden": "27",
      "dia": "2",
      "area": "B",
      "pabellon": "11.2",
      "stand": "11.2L34",
      "proveedor": "HEBEI BAOFENG STEEL STRUCTURE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Estructuras y módulos",
      "descripcion": "Estructuras de acero y soluciones prefabricadas; modelos y sistemas a confirmar.",
      "otrosStands": "F1: 19.1D19",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "9",
      "orden": "28",
      "dia": "2",
      "area": "B",
      "pabellon": "11.2",
      "stand": "11.2M03",
      "proveedor": "Anping County Huijin Wire Mesh Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Mallas metálicas",
      "descripcion": "Mallas y cerramientos metálicos; tipos de tejido y acabado a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "84",
      "orden": "29",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1B40",
      "proveedor": "ORIENT ALUMINIUM (QINGDAO) CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Aluminio",
      "descripcion": "Productos de aluminio para construcción; catálogo específico a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "45",
      "orden": "30",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1E39",
      "proveedor": "JIANGSU TIANYU FIBRE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Fibra de vidrio",
      "descripcion": "Mallas de fibra de vidrio, cintas y productos de refuerzo para construcción.",
      "otrosStands": "F1: 11.1I21",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "14",
      "orden": "31",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1F11-12，12.1E31-32",
      "proveedor": "NEWTECHWOOD CORPORATION",
      "visita": "Principal en esta fase",
      "rubro": "WPC",
      "descripcion": "Decks, revestimientos y soluciones exteriores de madera compuesta.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "47",
      "orden": "32",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1G04-05，12.1F39-40",
      "proveedor": "Durable Window Industry Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Aberturas",
      "descripcion": "Puertas y ventanas; materiales, herrajes y prestaciones a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "42",
      "orden": "33",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1G43-44",
      "proveedor": "3H Inc.",
      "visita": "Principal en esta fase",
      "rubro": "Herrajes para aberturas",
      "descripcion": "Manijas, bisagras, cierres y sistemas de herrajes para puertas y ventanas.",
      "otrosStands": "F1: 11.1G15-16",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "49",
      "orden": "34",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1H05-06",
      "proveedor": "Zhongshan Broad Curtain Wall & Windows & Doors System Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Aberturas y fachadas",
      "descripcion": "Sistemas de puertas, ventanas y muros cortina para construcción.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "86",
      "orden": "35",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1K09-10",
      "proveedor": "Foshan Wanjia Window and Door Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Aberturas",
      "descripcion": "Puertas y ventanas para proyectos residenciales y comerciales.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "52",
      "orden": "36",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1K37",
      "proveedor": "GUANGDONG GALUMINIUM EXTRUSION CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Aluminio",
      "descripcion": "Perfiles de aluminio extruido para aplicaciones arquitectónicas e industriales.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "85",
      "orden": "37",
      "dia": "3",
      "area": "B",
      "pabellon": "12.1",
      "stand": "12.1L01",
      "proveedor": "ORIENT ALUMINIUM (WEIFANG) CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Aluminio",
      "descripcion": "Perfiles y soluciones de aluminio; catálogo específico a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "75",
      "orden": "38",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1B35-36，13.1C10-11",
      "proveedor": "HEBEI MINMETALS CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Metales y ferretería",
      "descripcion": "Proveedor de artículos metálicos y ferretería; línea concreta a confirmar.",
      "otrosStands": "F3: 9.1L37; F1: 9.2F45; F1: 13.1A08-10，13.1B13-15; F1: 12.1L08; F2: 8.1D37-38，8.1E11-12; F2: 11.3K30",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "74",
      "orden": "39",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1E10-11，13.1D37-38",
      "proveedor": "LINYI CONSMOS IMP. & EXP. CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Tableros y revestimientos",
      "descripcion": "Comercialización internacional de tableros y materiales de madera; catálogo a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "101",
      "orden": "40",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1E41-42",
      "proveedor": "GETO New Materials Group",
      "visita": "Principal en esta fase",
      "rubro": "Encofrados",
      "descripcion": "Encofrados de aluminio y moldes PPVC/MIC; revisar sistema, reutilización y soporte técnico.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "11",
      "orden": "41",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1F23-24，13.1E23-24",
      "proveedor": "ZHEJIANG MINGDAO ALUMINIUM CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Aluminio",
      "descripcion": "Productos y perfiles de aluminio para construcción; sistemas a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "31",
      "orden": "42",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1I28",
      "proveedor": "Baoding Xinhai Plastic Sheet Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Placas plásticas",
      "descripcion": "Placas plásticas para cerramientos y cubiertas; polímero y espesores a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "4",
      "orden": "43",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1J09-10，13.1I39-40",
      "proveedor": "ZHUHAI GRAND KITCHENWARE CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Cocina",
      "descripcion": "Artículos y equipamiento de cocina; catálogo y materiales a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "28",
      "orden": "44",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1K07-08",
      "proveedor": "Dalian Quacent New Building Materials Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Construcción modular",
      "descripcion": "Sistemas de construcción prefabricada y paneles; composición y kits disponibles a confirmar.",
      "otrosStands": "F2: 13.0B03-04",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "22",
      "orden": "45",
      "dia": "3",
      "area": "B",
      "pabellon": "13.1",
      "stand": "13.1L11-12，13.1K35-36",
      "proveedor": "GUANXIAN RENZE COMPOSITE MATERIALS CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Chapas de acero",
      "descripcion": "Bobinas y chapas galvanizadas, aluminizadas y prepintadas.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "53",
      "orden": "46",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2B03",
      "proveedor": "BRD NEW MATERIALS CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Paneles constructivos",
      "descripcion": "Paneles y materiales para cubiertas y cerramientos; núcleos y prestaciones a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "100",
      "orden": "47",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2B14-15",
      "proveedor": "Vanjoin Hubei High Tech",
      "visita": "Principal en esta fase",
      "rubro": "Paneles prefabricados",
      "descripcion": "Paneles y sistemas de construcción livianos; evaluar muestras, juntas y alcance de suministro.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "5",
      "orden": "48",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2C08-13",
      "proveedor": "HUIDA SANITARY WARE CO., LTD.",
      "visita": "Alternativa / otra línea",
      "rubro": "Sanitarios",
      "descripcion": "Sanitarios cerámicos y equipamiento integral para baño.",
      "otrosStands": "F2: 10.1A08-17",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "77",
      "orden": "49",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2D31-36，13.2E12-16",
      "proveedor": "Oppein Home Group Inc.",
      "visita": "Principal en esta fase",
      "rubro": "Muebles de cocina",
      "descripcion": "Mobiliario para cocinas, armarios y soluciones de muebles para el hogar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "62",
      "orden": "50",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2D37-39，13.2E09-11",
      "proveedor": "GUANGDONG KITO CERAMICS GROUP CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Cerámicos",
      "descripcion": "Cerámicos y porcelanatos para pisos y revestimientos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "17",
      "orden": "51",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2E39-40，13.2F07-08",
      "proveedor": "HUIZHOU WEIKANG NEW BUILDING MATERIALS CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Pisos vinílicos",
      "descripcion": "Pisos plásticos y compuestos para interiores; formatos actuales a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "57",
      "orden": "52",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2E44-46",
      "proveedor": "FOSHAN JBN INDUSTRIAL CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Materiales de construcción",
      "descripcion": "Materiales para construcción y terminaciones; catálogo seleccionado a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "56",
      "orden": "53",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2F33-35，13.2G13-15",
      "proveedor": "GUANGDONG OVERLAND CERAMICS CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Cerámicos",
      "descripcion": "Cerámicos y porcelanatos para pisos y revestimientos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "18",
      "orden": "54",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2F43",
      "proveedor": "HEYUAN DONGYUAN EAGLE BRAND CERAMIC CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Cerámicos",
      "descripcion": "Cerámicos y porcelanatos para pisos y paredes.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "16",
      "orden": "55",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2G21-22，13.2F27-28",
      "proveedor": "JIANGSU KENTIER WOOD CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Pisos",
      "descripcion": "Pisos de madera y soluciones para pavimentos interiores; catálogo a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "83",
      "orden": "56",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2H31-32，13.2I17-18",
      "proveedor": "BARANA INTERNATIONAL LTD",
      "visita": "Alternativa / otra línea",
      "rubro": "Baño y terminaciones",
      "descripcion": "Productos para baño y construcción; catálogo seleccionado a confirmar.",
      "otrosStands": "F2: 11.1C37-38",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "65",
      "orden": "57",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2I10，13.2H38",
      "proveedor": "FOSHAN HAPPY HOUSE BUILDING MATERIALS CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Materiales de construcción",
      "descripcion": "Materiales de construcción y terminaciones; líneas específicas a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "43",
      "orden": "58",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2K19",
      "proveedor": "TAIZHOU YUANGUAN RUBBER PLASTIC CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Caucho y plásticos",
      "descripcion": "Productos de caucho y plástico; aplicación constructiva y catálogo a confirmar.",
      "otrosStands": "F3: 4.1Y11-12",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "58",
      "orden": "59",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2L12",
      "proveedor": "LINYI CONSMOS WOOD INDUSTRY CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Tableros de madera",
      "descripcion": "Tableros y productos de madera para obra, mobiliario y terminaciones.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "21",
      "orden": "60",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2L15",
      "proveedor": "Hangzhou Mitsein Wood Flooring Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Pisos de madera",
      "descripcion": "Pisos de madera; especies, capas y acabados a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "98",
      "orden": "61",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2L21",
      "proveedor": "Shandong Tianyi Machinery TANY",
      "visita": "Principal en esta fase",
      "rubro": "Prefabricados",
      "descripcion": "Líneas de paneles cemento/EPS, AAC, GRC, yeso y elementos prefabricados PC.",
      "otrosStands": "F1: 20.1J42",
      "fase": "Fase 2",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "81",
      "orden": "62",
      "dia": "4",
      "area": "B",
      "pabellon": "13.2",
      "stand": "13.2L23",
      "proveedor": "Linyi XHWOOD International Trade Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Paneles y revestimientos",
      "descripcion": "Bambú compuesto, WPC, acústicos, PVC, SPC, piedra 3D y WPC exterior.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "1",
      "orden": "63",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2B31-33",
      "proveedor": "KANGTON INDUSTRY, INC.",
      "visita": "Principal en esta fase",
      "rubro": "Pisos y puertas",
      "descripcion": "Pisos y puertas para proyectos residenciales y comerciales.",
      "otrosStands": "F1: 10.2J17-18",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "3",
      "orden": "64",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2C08-09，12.2B37-38",
      "proveedor": "Anhui Sentai WPC Group Share Co., LTD",
      "visita": "Principal en esta fase",
      "rubro": "WPC",
      "descripcion": "Decks y revestimientos de compuesto de madera y plástico para exteriores.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "20",
      "orden": "65",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2C22",
      "proveedor": "Hebei MacroTech Wood Plastic Composite Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "WPC",
      "descripcion": "Productos de compuesto madera-plástico para decks y revestimientos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "120",
      "orden": "66",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2D48",
      "proveedor": "Linyi Luju Leader Wood",
      "visita": "Principal en esta fase",
      "rubro": "Fibrocemento y madera",
      "descripcion": "Ofrece fibrocemento dentro de catálogo principalmente de madera; confirmar planta y fabricación propia.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "37",
      "orden": "67",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2E15-17",
      "proveedor": "Henan Beidi Plastic Industry Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Perfiles PVC",
      "descripcion": "Perfiles plásticos para puertas y ventanas; sistemas y prestaciones a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "44",
      "orden": "68",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2E31-33，12.2F10-12",
      "proveedor": "Shanghai Alubang Decorative Material Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Paneles de aluminio",
      "descripcion": "Paneles decorativos de aluminio y materiales para fachadas; composición a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "66",
      "orden": "69",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2G07-08",
      "proveedor": "Anji Zhengyuan WPC Decoration Material Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "WPC",
      "descripcion": "Materiales decorativos de compuesto madera-plástico.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "15",
      "orden": "70",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2H31-32",
      "proveedor": "JIANGSU PARKMAN WOODS INDUSTRY CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Pisos de madera",
      "descripcion": "Pisos y productos de madera para terminaciones; líneas a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "29",
      "orden": "71",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2H36-37",
      "proveedor": "CHANGZHOU OUDELONG DECORATIVE MATERIAL CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Pisos y decoración",
      "descripcion": "Materiales decorativos y pisos; líneas SPC, vinílicas o laminadas a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "13",
      "orden": "72",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2J42",
      "proveedor": "ZERUITANGFLOOR",
      "visita": "Principal en esta fase",
      "rubro": "Pisos",
      "descripcion": "Proveedor de pisos; composición, formatos y sistema de instalación a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "80",
      "orden": "73",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2K06",
      "proveedor": "Shijiazhuang Decno Decoration Material Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Pisos",
      "descripcion": "Pisos SPC, paneles SPC para pared y paneles acústicos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "103",
      "orden": "74",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2K09",
      "proveedor": "Hebei YuNiu Fiberglass",
      "visita": "Principal en esta fase",
      "rubro": "Refuerzo",
      "descripcion": "Fibras de vidrio; confirmar resistencia a álcalis, uso en cemento, dosificación y ensayos.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Stand indicado en documento 140",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "41",
      "orden": "75",
      "dia": "4",
      "area": "B",
      "pabellon": "12.2",
      "stand": "12.2K47",
      "proveedor": "CHONGNUO (SHANDONG) NEW MATERIAL CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Pisos SPC",
      "descripcion": "Pisos SPC, zócalos, molduras y accesorios para instalación.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "68",
      "orden": "76",
      "dia": "5",
      "area": "B",
      "pabellon": "10.2",
      "stand": "10.2I39-41",
      "proveedor": "FOSHAN SHENGDA ECONOMY COMMERCE LTD",
      "visita": "Principal en esta fase",
      "rubro": "Comercializadora multirrubro",
      "descripcion": "Comercializadora de productos variados; catálogo y fase del producto de interés pendientes.",
      "otrosStands": "F2: 20.1H38-40",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "10",
      "orden": "77",
      "dia": "5",
      "area": "B",
      "pabellon": "11.3",
      "stand": "11.3B27-28",
      "proveedor": "Tengzhou Yoway Electronic Technology Co., LTD",
      "visita": "Alternativa / otra línea",
      "rubro": "Espejos y muebles de baño",
      "descripcion": "Espejos iluminados y gabinetes para baño.",
      "otrosStands": "F2: 10.1D01-03",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "69",
      "orden": "78",
      "dia": "5",
      "area": "B",
      "pabellon": "11.3",
      "stand": "11.3B35-36，11.3C12-13",
      "proveedor": "LUMI LEGEND CORPORATION",
      "visita": "Principal en esta fase",
      "rubro": "Soportes y ergonomía",
      "descripcion": "Soportes para pantallas y soluciones de montaje y ergonomía.",
      "otrosStands": "F1: 20.2H37-39，20.2I10-12",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "75",
      "orden": "79",
      "dia": "5",
      "area": "B",
      "pabellon": "11.3",
      "stand": "11.3K30",
      "proveedor": "HEBEI MINMETALS CO., LTD.",
      "visita": "Alternativa / otra línea",
      "rubro": "Metales y ferretería",
      "descripcion": "Proveedor de artículos metálicos y ferretería; línea concreta a confirmar.",
      "otrosStands": "F3: 9.1L37; F1: 9.2F45; F1: 13.1A08-10，13.1B13-15; F1: 12.1L08; F2: 8.1D37-38，8.1E11-12; F2: 13.1B35-36，13.1C10-11",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "89",
      "orden": "80",
      "dia": "5",
      "area": "B",
      "pabellon": "12.0",
      "stand": "12.0A10",
      "proveedor": "Shandong China Transport Group Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Maquinaria",
      "descripcion": "Maquinaria y equipos industriales; catálogo de interés a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "54",
      "orden": "81",
      "dia": "5",
      "area": "B",
      "pabellon": "12.0",
      "stand": "12.0C11-12，12.0D11",
      "proveedor": "Wiskind Architectural Steel Co., Ltd.",
      "visita": "Alternativa / otra línea",
      "rubro": "Paneles y chapas",
      "descripcion": "Sistemas metálicos, paneles y envolventes para edificios.",
      "otrosStands": "F2: 11.2L16",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "82",
      "orden": "82",
      "dia": "5",
      "area": "B",
      "pabellon": "13.0",
      "stand": "13.0A22-23，13.0B01-02",
      "proveedor": "Foshan Greenzone Co., LTD",
      "visita": "Principal en esta fase",
      "rubro": "WPC",
      "descripcion": "Soluciones decorativas de madera compuesta; decks, revestimientos y otros formatos a confirmar.",
      "otrosStands": "F1: 1.1M04",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "28",
      "orden": "83",
      "dia": "5",
      "area": "B",
      "pabellon": "13.0",
      "stand": "13.0B03-04",
      "proveedor": "Dalian Quacent New Building Materials Co., Ltd.",
      "visita": "Alternativa / otra línea",
      "rubro": "Construcción modular",
      "descripcion": "Sistemas de construcción prefabricada y paneles; composición y kits disponibles a confirmar.",
      "otrosStands": "F2: 13.1K07-08",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "33",
      "orden": "84",
      "dia": "5",
      "area": "B",
      "pabellon": "13.0",
      "stand": "13.0C01",
      "proveedor": "Xuzhou Longer New Material Co., Ltd.",
      "visita": "Principal en esta fase",
      "rubro": "Materiales de construcción",
      "descripcion": "Nuevos materiales para construcción y terminaciones; familia exacta a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "50",
      "orden": "85",
      "dia": "5",
      "area": "A",
      "pabellon": "8.0",
      "stand": "8.0H27",
      "proveedor": "SHANDONG ORIENT ALUMINIUM CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Aluminio",
      "descripcion": "Perfiles y productos de aluminio para construcción; familias a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "75",
      "orden": "86",
      "dia": "5",
      "area": "A",
      "pabellon": "8.1",
      "stand": "8.1D37-38，8.1E11-12",
      "proveedor": "HEBEI MINMETALS CO., LTD.",
      "visita": "Alternativa / otra línea",
      "rubro": "Metales y ferretería",
      "descripcion": "Proveedor de artículos metálicos y ferretería; línea concreta a confirmar.",
      "otrosStands": "F3: 9.1L37; F1: 9.2F45; F1: 13.1A08-10，13.1B13-15; F1: 12.1L08; F2: 11.3K30; F2: 13.1B35-36，13.1C10-11",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "79",
      "orden": "87",
      "dia": "5",
      "area": "D",
      "pabellon": "17.1",
      "stand": "17.1B34-35，17.1C10-11",
      "proveedor": "ZHEJIANG WANGBIN DECORATIVE MATERIAL CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Decoración",
      "descripcion": "Materiales decorativos; molduras, marcos y productos específicos a confirmar.",
      "otrosStands": "",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "68",
      "orden": "88",
      "dia": "5",
      "area": "D",
      "pabellon": "20.1",
      "stand": "20.1H38-40",
      "proveedor": "FOSHAN SHENGDA ECONOMY COMMERCE LTD",
      "visita": "Alternativa / otra línea",
      "rubro": "Comercializadora multirrubro",
      "descripcion": "Comercializadora de productos variados; catálogo y fase del producto de interés pendientes.",
      "otrosStands": "F2: 10.2I39-41",
      "fase": "Fase 2",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    }
  ],
  "Fase 3": [
    {
      "id": "43",
      "orden": "1",
      "dia": "1",
      "area": "A",
      "pabellon": "4.1",
      "stand": "4.1Y11-12",
      "proveedor": "TAIZHOU YUANGUAN RUBBER PLASTIC CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Caucho y plásticos",
      "descripcion": "Productos de caucho y plástico; aplicación constructiva y catálogo a confirmar.",
      "otrosStands": "F2: 13.2K19",
      "fase": "Fase 3",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "75",
      "orden": "2",
      "dia": "1",
      "area": "B",
      "pabellon": "9.1",
      "stand": "9.1L37",
      "proveedor": "HEBEI MINMETALS CO., LTD.",
      "visita": "Principal en esta fase",
      "rubro": "Metales y ferretería",
      "descripcion": "Proveedor de artículos metálicos y ferretería; línea concreta a confirmar.",
      "otrosStands": "F1: 9.2F45; F1: 13.1A08-10，13.1B13-15; F1: 12.1L08; F2: 8.1D37-38，8.1E11-12; F2: 11.3K30; F2: 13.1B35-36，13.1C10-11",
      "fase": "Fase 3",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "88",
      "orden": "3",
      "dia": "1",
      "area": "B",
      "pabellon": "9.2",
      "stand": "9.2B23-24，9.2A01-02",
      "proveedor": "GUANGZHOU MONALISA BATH WARE CO., LTD",
      "visita": "Principal en esta fase",
      "rubro": "Baño e hidromasaje",
      "descripcion": "Equipamiento de baño e hidromasaje; modelos y catálogo a confirmar.",
      "otrosStands": "F2: 10.1E32-38，10.1F13-19; F2: 9.0C01-02",
      "fase": "Fase 3",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    },
    {
      "id": "2",
      "orden": "4",
      "dia": "1",
      "area": "B",
      "pabellon": "10.2",
      "stand": "10.2F48",
      "proveedor": "Guangzhou Selaqua Sanitary Ware Co., Ltd",
      "visita": "Principal en esta fase",
      "rubro": "Sanitarios",
      "descripcion": "Equipamiento sanitario y productos para baño; líneas específicas a confirmar.",
      "otrosStands": "F2: 11.1H13-16，11.1G31-34",
      "fase": "Fase 3",
      "estadoStand": "Publicado en Canton Fair 365",
      "enlace": "Ver proveedor y stands"
    }
  ],
  "Por confirmar": [
    {
      "id": "48",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Xuchang Gutenai Machinery Co., Ltd.",
      "visita": "Principal",
      "rubro": "Maquinaria",
      "descripcion": "Empresa de maquinaria; nombre legal, producto principal y fase pendientes de confirmar.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Online only",
      "enlace": "Ver proveedor"
    },
    {
      "id": "51",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Huacheng BoYuan Hebei Building Materials Technology Co., Ltd",
      "visita": "Principal",
      "rubro": "Materiales de construcción",
      "descripcion": "Materiales constructivos; sistemas y productos concretos a confirmar.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Online only",
      "enlace": "Ver proveedor"
    },
    {
      "id": "78",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "GUANGDONG MONALISA TRADING CO., LTD",
      "visita": "Principal",
      "rubro": "Cerámicos",
      "descripcion": "Comercialización de cerámicos y revestimientos; líneas actuales a confirmar.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Online only",
      "enlace": "Ver proveedor"
    },
    {
      "id": "106",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Liaoning Metal Technology",
      "visita": "Principal",
      "rubro": "Cilindros",
      "descripcion": "Aluminio sin costura y compuestos de fibra de carbono. Presencia 140 pendiente; no usar stand 139.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "107",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Snowrain",
      "visita": "Principal",
      "rubro": "Cilindros",
      "descripcion": "Cilindros de alta presión para gases industriales, oxígeno, CO₂ y buceo; stand 140 pendiente.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "108",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Hubei DALY Cylinder",
      "visita": "Principal",
      "rubro": "GLP y refrigerantes",
      "descripcion": "Cilindros de acero GLP, refrigerantes y tanques de autogás; stand 140 pendiente.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "109",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Shanghai Wonder Gas",
      "visita": "Principal",
      "rubro": "Gases y cilindros",
      "descripcion": "Gases industriales, mezclas y recipientes; identificar fabricante de tubos. Stand 140 pendiente.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "110",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Smart Pioneer",
      "visita": "Principal",
      "rubro": "Criogenia",
      "descripcion": "Tanques y equipos de almacenamiento y transporte de gases líquidos; presencia y stand 140 pendientes.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "111",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Olymtech",
      "visita": "Principal",
      "rubro": "Compresores y nitrógeno",
      "descripcion": "Compresores de aire y generadores PSA; anuncia Cantón 140, stand pendiente.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "117",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Jiangsu Zhengjun River Flooring",
      "visita": "Principal",
      "rubro": "Pisos y paredes SPC",
      "descripcion": "Alternativa a DECNO para comparar sistemas SPC. Stand 140 pendiente; no usar ubicación 139.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "118",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Zhanjiang Boardway",
      "visita": "Principal",
      "rubro": "Placas PVC",
      "descripcion": "PVC espumado, placas decorativas laminadas y molduras; stand 140 pendiente, antecedente 138.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "119",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Guangdong New Element",
      "visita": "Principal",
      "rubro": "Placas minerales",
      "descripcion": "Backerpan fibrocemento para base en zonas húmedas y silicato cálcico; presencia 140 sin confirmar.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "121",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Guangdong Eagle Brand / Eagle Ceramics",
      "visita": "Principal",
      "rubro": "Panel decorativo",
      "descripcion": "ECOEAGLE Diatom Wall Panel, núcleo técnico de diatomeas; no asumir placa evaporadora. Stand 140 pendiente.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    },
    {
      "id": "122",
      "orden": "",
      "dia": "1",
      "area": "",
      "pabellon": "",
      "stand": "",
      "proveedor": "Sanle (Foshan, Guangdong)",
      "visita": "Principal",
      "rubro": "Placas minerales",
      "descripcion": "Silicato cálcico y fibrocemento; sin evidencia suficiente de participación. Placa capilar activa no verificada.",
      "otrosStands": "",
      "fase": "Por confirmar",
      "estadoStand": "Presencia / stand 140 pendiente",
      "enlace": "Ver documento aportado"
    }
  ]
};
